### ISSUE TITLE
Check task description and template provided for students

### ISSUE THREAD

**Issue by PTOoster** [geoscripting-innovation/Exercise1-starter#1]
Could you please check the task description? Also, is the template provided to the students good enough, or should we provide more/less project structure?

**Comment by GreatEmerald** [comment]
I think you can also add a `source(R/ageCalculator.R)` into `main.R`, so as to make it a bit more clear what is expected from the students.
Also, in the readme you have `is.leap` instead of `ageCalculator` for the last example ;)

Otherwise I think it looks good.

**Comment by PTOoster** [comment]
Thanks for feedback! Changes implemented.
